// Cloudflare Pages Function — matches Express route response shape
export async function onRequestPost({ request }) {
  let body = {};
  try { body = await request.json(); } catch {}

  const result = {
    primaryCause: body.symptoms ? 'Cloudflare fallback diagnosis' : 'No symptoms provided',
    secondaryCauses: [],
    codeExplanations: {},
    recommendedTests: body.symptoms ? ['Visual inspection'] : [],
    recommendedRepairs: [],
    urgency: 'soon',
    safetyRisk: false,
    estimatedRepairTime: 'unknown',
    notes: 'Generated by Cloudflare Pages (offline mode)'
  };

  return Response.json({ success: true, result });
}
