// Cloudflare Pages Function — matches Express route response shape
export async function onRequestPost({ request, env }) {
  let body = {};
  try { body = await request.json(); } catch {}

  const laborRate = Math.max(0, Number(body.laborRate || body.labor || env.DEFAULT_LABOR_RATE || 65));
  const partsCost = Math.max(0, Number(body.partsCost || body.parts || 0));

  // Build response matching Express route shape
  const estimate = {
    diagnosis: body.customerStates || body.symptoms ? 'Cloudflare fallback estimate' : 'No symptoms provided',
    repairs: body.customerStates || body.symptoms ? ['Service recommended'] : [],
    estimatedHours: 1,
    laborCost: Math.round(laborRate * 100) / 100,
    partsCost: Math.round(partsCost * 100) / 100,
    total: Math.round((laborRate + partsCost) * 100) / 100,
    notes: 'Generated by Cloudflare Pages (offline mode)',
    priority: 'medium'
  };

  return Response.json({ success: true, estimate });
}
