/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/invoice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate invoice PDF
         * @description Endpoint /api/invoice POST operation
         */
        post: operations["createInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run local diagnostics and return repair guidance
         * @description Endpoint /api/diagnose POST operation
         */
        post: operations["runDiagnose"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/estimateHeuristic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Heuristic estimate engine
         * @description Endpoint /api/estimateHeuristic POST operation
         */
        post: operations["createEstimate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example false */
            success?: boolean;
            error?: string;
            details?: string;
            /** @description Correlation id for logs */
            trace?: string;
        };
        Customer: {
            name?: string;
            phone?: string;
        };
        Part: {
            name?: string;
            /** Format: float */
            cost?: number;
        };
        InvoiceRequest: {
            customer: components["schemas"]["Customer"];
            vehicle: {
                year?: number;
                make?: string;
                model?: string;
                trim?: string;
            };
            mileage?: number;
            obdCodes?: string[];
            symptoms?: string[];
            /** Format: float */
            laborRate?: number;
            /** Format: float */
            estimatedHours?: number;
            /** Format: float */
            partsCost?: number;
            parts?: components["schemas"]["Part"][];
            id: string;
        };
        InvoiceResponse: {
            /** @example true */
            success?: boolean;
            invoiceId?: string;
            pdfUrl?: string;
            id: string;
        };
        DiagnoseRequest: {
            vehicle?: {
                year?: number;
                make?: string;
                trim?: string;
            };
            obdCodes?: string[];
            customerStates?: string[];
            id: string;
        };
        DiagnoseResult: {
            /** @example true */
            success?: boolean;
            result?: {
                localVehicleTelemetry?: {
                    vehicleId?: string;
                };
                primaryCause?: string;
                notes?: string;
                repairSteps?: string[];
            };
        };
        EstimateRequest: {
            vehicle?: Record<string, never>;
            obdCodes?: string[];
            jobContext?: Record<string, never>;
            id: string;
        };
        EstimateResponse: {
            success?: boolean;
            estimateId?: string;
            /** Format: float */
            total?: number;
            breakdown?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "customer": {
                 *         "name": "Johnny Castaway",
                 *         "phone": "330-555-0199"
                 *       },
                 *       "vehicle": {
                 *         "year": 2012,
                 *         "make": "Ram",
                 *         "model": "1500",
                 *         "trim": "Laramie 5.7L"
                 *       },
                 *       "mileage": 142500,
                 *       "obdCodes": [
                 *         "P0303"
                 *       ],
                 *       "symptoms": [
                 *         "Lifter Tick",
                 *         "Misfire under load"
                 *       ],
                 *       "laborRate": 85,
                 *       "estimatedHours": 12,
                 *       "partsCost": 485.5,
                 *       "parts": [
                 *         {
                 *           "name": "Mopar Camshaft (53022263AF)",
                 *           "cost": 225
                 *         },
                 *         {
                 *           "name": "Mopar MDS Lifter Yoke Set",
                 *           "cost": 260.5
                 *         }
                 *       ],
                 *       "id": "example-id-1"
                 *     }
                 */
                "application/json": components["schemas"]["InvoiceRequest"];
            };
        };
        responses: {
            /** @description PDF invoice binary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                    "application/json": components["schemas"]["InvoiceResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runDiagnose: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "vehicle": {
                 *         "year": 2012,
                 *         "make": "Ram",
                 *         "trim": "hemi"
                 *       },
                 *       "obdCodes": [
                 *         "P0303"
                 *       ],
                 *       "customerStates": [
                 *         "lifter tick",
                 *         "misfire"
                 *       ],
                 *       "id": "example-id-1"
                 *     }
                 */
                "application/json": components["schemas"]["DiagnoseRequest"];
            };
        };
        responses: {
            /** @description Diagnostic result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnoseResult"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description External dependency not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createEstimate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "vehicle": {
                 *         "year": 2012,
                 *         "make": "Ram",
                 *         "trim": "hemi"
                 *       },
                 *       "obdCodes": [
                 *         "P0303"
                 *       ],
                 *       "jobContext": {
                 *         "urgency": "standard"
                 *       },
                 *       "id": "example-id-1"
                 *     }
                 */
                "application/json": components["schemas"]["EstimateRequest"];
            };
        };
        responses: {
            /** @description Estimate result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstimateResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
