services:
  - type: web
    name: sksk-backend
    env: docker
    dockerfilePath: Dockerfile
    plan: starter

    buildCommand: ""

    startCommand: node server.js

    envVars:
      - key: PORT
        value: "10000"

      - key: LEMON_PATH
        value: "/opt/lemon_scraper/lemon_scraper"

      - key: NODE_ENV
        value: "production"

    healthCheckPath: /health
    autoDeploy: true

  - type: worker
    name: sksk-scraper-worker
    env: docker
    dockerfilePath: Dockerfile
    plan: starter

    buildCommand: ""

    startCommand: node worker/scrape-worker.js

    envVars:
      - key: LEMON_PATH
        value: "/opt/lemon_scraper/lemon_scraper"

      - key: NODE_ENV
        value: "production"

    autoDeploy: true
